"use strict";
const assert = require('assert').strict;
const { transition, warning, retryDelay } = require('../segmented_frontend/camera_sync_ui.js');

assert.deepEqual(transition(null,{status:'ready',generation:3}), {generation:3,refresh:true,status:'ready'});
assert.deepEqual(transition({generation:3},{status:'ready',generation:3}), {generation:3,refresh:false,status:'ready'});
assert.deepEqual(transition({generation:3},{status:'desynced',generation:3}), {generation:3,refresh:false,status:'desynced'});
assert(/不同步/.test(warning({status:'desynced',skew_ms:187})));
assert(/冻结/.test(warning({status:'frozen',last_advance_age_sec:2.4})));
assert(/过期/.test(warning({status:'stale',stale_keys:['camera_left']})));
assert.equal(warning({status:'ready',skew_ms:40}), '三相机同步 · skew 40 ms');
assert.equal(retryDelay('ready',3), 500);
assert.equal(retryDelay('unavailable',0), 250);
assert.equal(retryDelay('unavailable',5), 2000);
console.log('PASS synchronized camera UI state, warnings, and bounded retry');

const { JSDOM } = require('jsdom');
const { renderHealth,cameraStatus } = require('../segmented_frontend/camera_sync_ui.js');
const dom=new JSDOM('<figure><img data-camera="camera_left"/></figure><figure><img data-camera="camera_right"/></figure>');
const state={status:'degraded',cameras:{camera_left:{status:'ready',generation:2},camera_high:{status:'ready',generation:3},camera_right:{status:'stale',generation:1}}};
renderHealth(dom.window.document,state);
const left=dom.window.document.querySelector('[data-camera="camera_left"]');
const right=dom.window.document.querySelector('[data-camera="camera_right"]');
assert.equal(left.dataset.cameraStatus,'ready');
assert(left.closest('figure').querySelector('.camera-unavailable-message').hidden);
assert.equal(right.dataset.cameraStatus,'stale');
assert(!right.closest('figure').querySelector('.camera-unavailable-message').hidden);
assert(warning(state).includes('其余 2 路继续预览'));
assert.equal(retryDelay('degraded',5),500);
state.cameras.camera_right.status='ready';
renderHealth(dom.window.document,state);
assert(right.closest('figure').querySelector('.camera-unavailable-message').hidden);
assert.equal(dom.window.document.querySelectorAll('.camera-unavailable-message').length,2);
assert.equal(cameraStatus(state,'camera_right'),'ready');
console.log('PASS independent preview health and reconnect labels');

const fs=require('fs'),vm=require('vm');
const source=fs.readFileSync(require.resolve('../segmented_frontend/app.js'),'utf8');
const streamCode=source.slice(source.indexOf('function syncCameraStreams()'),source.indexOf('function loadCameraGeneration('));
const view=new JSDOM('<section data-page="operation" class="active"><div id="camera-dock"><figure><img data-camera="camera_left"/></figure><figure><img data-camera="camera_right"/></figure></div></section>',{pretendToBeVisual:true,url:'http://localhost/'});
view.window.CobotWorkspaceUI={cameraVisible:()=>true};
view.window.CobotCameraSyncUI=require('../segmented_frontend/camera_sync_ui.js');
const ctx=vm.createContext({window:view.window,document:view.window.document,Date,setTimeout:()=>0,$$:selector=>Array.from(view.window.document.querySelectorAll(selector))});
const ui=view.window.CobotCameraSyncUI;
const normal={status:'ready',cameras:{camera_left:{status:'ready'},camera_right:{status:'ready'}}};
ui.renderHealth(view.window.document,normal);
vm.runInContext(streamCode,ctx);
vm.runInContext('syncCameraStreams()',ctx);
const liveLeft=view.window.document.querySelector('[data-camera="camera_left"]');
const liveRight=view.window.document.querySelector('[data-camera="camera_right"]');
const leftSource=liveLeft.src;
assert(liveRight.src.includes('.mjpg'));
normal.status='degraded';normal.cameras.camera_right.status='stale';
ui.renderHealth(view.window.document,normal);
vm.runInContext('syncCameraStreams()',ctx);
assert.equal(liveLeft.src,leftSource);
assert(!liveRight.hasAttribute('src'));
assert.equal(liveLeft.dataset.streaming,'true');
liveLeft.dataset.blankSince=String(Date.now()-2000);
ctx.partial=normal;
vm.runInContext('repairBlankCameraStreams(partial)',ctx);
assert.equal(liveLeft.dataset.streaming,'true');
assert(!liveRight.hasAttribute('src'));
normal.cameras.camera_right.status='ready';
ui.renderHealth(view.window.document,normal);
vm.runInContext('syncCameraStreams()',ctx);
assert(liveRight.src.includes('.mjpg'));
assert.equal(liveLeft.dataset.streaming,'true');
console.log('PASS actual stream DOM: partial dropout, blank stream repair and independent recovery');
